title: Happy Kemper
author:
  name: Bosse Kemper
  email: 'bosse@happykemper.com'
metadata:
    description: Via modern web-development creëren we samen jouw digitale uitingen. Van volledige websites tot (verhalende) web-animaties. Happy Kemper is een freelance developer, uit Rotterdam.

# Site settings
title: Happy Kemper
email: bosse@happykemper.com
description: Via modern web-development creëren we samen jouw digitale uitingen. Van volledige websites tot (verhalende) web-animaties. Happy Kemper is een freelance developer, uit Rotterdam.