title: Happy Kemper
author:
  name: Bosse Kemper
  email: 'bosse@happykemper.com'
metadata:
    description: 'Via modern webdevelopment helpt Happy Kemper met het creëren van jouw digitale uitingen. Van volledige websites tot (verhalende) webanimaties. Happy Kemper is gevestigd in rotterdam'

# Site settings
title: Happy Kemper
email: bosse@happykemper.com
description: "Via modern webdevelopment helpt Happy Kemper met het creëren van jouw digitale uitingen. Van volledige websites tot (verhalende) webanimaties. Happy Kemper is gevestigd in rotterdam"
