title: Happy Kemper
author:
  name: Bosse Kemper
  email: 'bosse@happykemper.com'
metadata:
    description: 'Place discription here'

# Site settings
title: Happy Kemper
email: bosse@happykemper.com
description: "Place discription here"
